server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/PodssilDev/Microservicios_Tingeso2
          search-paths: config-data
          username: PodssilDev
          password: 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
  application:
    name: config-service
