server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/PodssilDev/Microservicios_Tingeso2
          search-paths: config-data
          password: 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
          username: PodssilDev
  application:
    name: config-service
